name: GitHub Merge Actions
run-name: ${{github.actor}} pushed new stuff 🚀
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install
          npm run test
          npm run build
